name: Java_Maven_Build

on:
  push:
    branches: [ dingo-store-v3.1.0 ]
  pull_request:
    branches: [ dingo-store-v3.1.0 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Clone Submodule
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: git submodule update --init --recursive

    - name: Build with Maven
      run:  cd java && mvn clean compile -Dmaven.test.skip=true  #-DiskipTests
      # run: cd java && mvn -B package --file pom.xml


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
